In [1]:
import pandas as pd
import re

In [2]:
# Renaming dictionary
renaming_dict = {
    'Intercept': 'Intercept',
    'threshold': 'Threshold',
    'time_delta': 'Time Delta',
    'time_delta:threshold': 'Time Delta:Threshold',
    'weekday': 'Weekday',
    'quantile_pop_bins_percent_bachelor_home[T.High]': 'High SE class',
    'quantile_pop_bins_percent_bachelor_home[T.High]:threshold': 'High SE class:Threshold',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]': 'Medium SE class',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]:threshold': 'Medium SE class:Threshold',
    'I(time_delta ** 2)':'Time Delta ** 2',
    'I(time_delta ** 3)':'Time Delta ** 3',
    'treatment':'Treatment',
    'threshold:treatment':'Treatment:Threshold',
    'C(weekday)[T.1]':'Tuesday',
    'C(weekday)[T.2]':'Wednesday',
    'C(weekday)[T.3]':'Thursday',
    'C(weekday)[T.4]':'Friday',
    'C(weekday)[T.5]':'Saturday',
    'C(weekday)[T.6]':'Sunday',
    'time_delta:treatment':'Time Delta:Treatment',
    'first_day':'First Night (2-3 February)',
    'first_day:treatment': 'First Night:Treatment',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]:treatment':'Medium SE class:Treatment',
    'quantile_pop_bins_percent_bachelor_home[T.High]:treatment':'High SE class:Treatment',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]:treatment:threshold':'Medium SE class:Treatment:Threshold',
    'quantile_pop_bins_percent_bachelor_home[T.High]:treatment:threshold':'High SE class:Treatment:Threshold'
}

# Function to rename variables
def rename_variables(df, renaming_dict):
    df_renamed = df.rename(index=renaming_dict)
    return df_renamed


def modify_zeros(df):
    # Define a function to apply to each cell
    def replace_zero(value):
        if isinstance(value, str):
            return re.sub(r'\b0\.000(\*+)?\b', r'$<$0.001\1', value)
        return value
        
    modified_df = df.map(replace_zero)
    
    return modified_df

\textit{Notes:} Standard Errors are in parentheses. Standard Errors are heteroscedasticity and autocorrelation robust (HAC) using 1 lag. 

    *** p$<$0.001, ** p$<$0.01, * p$<$0.05.

In [3]:
regression_table1 = pd.read_csv('../data_created/regression_results/rdd_table1.csv')
regression_table1 = regression_table1.fillna(' ')

In [4]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[16:24, :],
                               regression_table1.iloc[8:16, :], regression_table1.iloc[0:4, :],
                               regression_table1.iloc[24:27, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [5]:
regression_table1 = rename_variables(regression_table1, renaming_dict)

In [6]:
regression_table1 = modify_zeros(regression_table1)

In [7]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 0.067*** & 0.164*** & 0.096*** & 0.074*** & 0.168*** & 0.102*** \\
  & (0.020) & (0.035) & (0.021) & (0.014) & (0.027) & (0.015) \\
Threshold & 0.267*** & 0.258*** & 0.351*** & 0.336*** & 0.328*** & 0.417*** \\
  & (0.064) & (0.054) & (0.051) & (0.038) & (0.031) & (0.034) \\
Time Delta & 0.001 & 0.033*** & 0.014* & 0.001 & 0.032*** & 0.013** \\
  & (0.002) & (0.009) & (0.006) & (0.001) & (0.007) & (0.004) \\
Time Delta:Threshold & -0.018** & -0.082*** & -0.069*** & -0.018*** & -0.080*** & -0.067*** \\
  & (0.006) & (0.019) & (0.013) & (0.004) & (0.015) & (0.011) \\
Weekday & 0.021*** & 0.019*** & 0.020*** & 0.021*** & 0.018*** & 0.019*** \\
  & (0.006) & (0.004) & (0.004) & (0.004) & (0.003) & (0.003) \\
High SE class &   &   &   & -0.010 & -0.010 & -0.010 \\
  &   &   &   & (0.009) & (0.013) & (0.008) \\
High SE class:Threshold &   &   &   & -0.098*** & -0.098*** & -0.098*** \\
  &   &   &   & (0.028) & (0.027) & (0.025) \\
Medium SE class &   &   &   & -0.007 & -0.007 & -0.007 \\
  &   &   &   & (0.007) & (0.011) & (0.007) \\
Medium SE class:Threshold &   &   &   & -0.070** & -0.070** & -0.070** \\
  &   &   &   & (0.026) & (0.024) & (0.023) \\
Time Delta ** 2 &   & 0.002*** & 0.002*** &   & 0.002*** & 0.002*** \\
  &   & (0.001) & ($<$0.001) &   & ($<$0.001) & ($<$0.001) \\
Time Delta ** 3 &   &   & $<$0.001*** &   &   & $<$0.001*** \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.750 & 0.852 & 0.894 & 0.738 & 0.816 & 0.850 \\
Adjusted R-squared & 0.714 & 0.823 & 0.869 & 0.714 & 0.797 & 0.832 \\
No. observations & 32 & 32 & 32 & 96 & 96 & 96 \\
\bottomrule
\end{tabular}

In [8]:
regression_table1 = pd.read_csv('../data_created/regression_results/did_table1.csv')
regression_table1 = regression_table1.fillna(' ')

In [9]:
regression_table1

,Unnamed: 0,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
0,I(time_delta ** 2),,-0.000,-0.000,,,-0.000**
1,,,(0.000),(0.000),,,(0.000)
2,I(time_delta ** 3),,,0.000*,,,0.000**
3,,,,(0.000),,,(0.000)
4,Intercept,0.006,0.024,-0.015,0.005,0.005,-0.014
5,,(0.033),(0.022),(0.037),(0.021),(0.021),(0.025)
6,R-squared,0.666,0.685,0.733,0.663,0.663,0.721
7,R-squared Adj.,0.637,0.652,0.699,0.639,0.639,0.697
8,quantile_pop_bins_percent_bachelor_home[T.High],,,,0.004,0.004,0.004
9,,,,,(0.009),(0.009),(0.008)
10,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.002,-0.002,-0.002
11,,,,,(0.013),(0.013),(0.014)
12,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.014,-0.014,-0.014
13,,,,,(0.014),(0.014),(0.012)
14,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.097**,-0.097**,-0.097**
15,,,,,(0.037),(0.037),(0.034)
16,quantile_pop_bins_percent_bachelor_home[T.Medium],,,,-0.003,-0.003,-0.003
17,,,,,(0.008),(0.008),(0.007)
18,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,0.002,0.002,0.002
19,,,,,(0.012),(0.012),(0.013)
20,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,-0.005,-0.005,-0.005
21,,,,,(0.012),(0.012),(0.012)
22,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,-0.072*,-0.072*,-0.072*
23,,,,,(0.033),(0.033),(0.031)
24,threshold,0.103*,0.094*,0.169*,0.106***,0.106***,0.170***
25,,(0.043),(0.037),(0.068),(0.029),(0.029),(0.046)
26,threshold:treatment,0.118***,0.118***,0.118***,0.181***,0.181***,0.181***
27,,(0.034),(0.033),(0.031),(0.030),(0.030),(0.027)
28,time_delta,-0.005,-0.004,-0.015*,-0.005**,-0.005**,-0.015**
29,,(0.003),(0.002),(0.007),(0.002),(0.002),(0.005)
30,treatment,0.031*,0.031**,0.031*,0.038**,0.038**,0.038***
31,,(0.014),(0.010),(0.014),(0.012),(0.012),(0.011)
32,weekday,0.015***,0.016***,0.017***,0.015***,0.015***,0.016***
33,,(0.004),(0.004),(0.004),(0.003),(0.003),(0.003)
34,R-squared,0.666,0.685,0.733,0.663,0.663,0.721
35,Adjusted R-squared,0.637,0.652,0.699,0.639,0.639,0.697
36,No. observations,64,64,64,192,192,192

In [10]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[24:34, :],
                               regression_table1.iloc[8:24, :], regression_table1.iloc[0:4, :],
                               regression_table1.iloc[34:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [11]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [12]:
regression_table1

,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
Variables,,,,,,
Intercept,0.006,0.024,-0.015,0.005,0.005,-0.014
,(0.033),(0.022),(0.037),(0.021),(0.021),(0.025)
Threshold,0.103*,0.094*,0.169*,0.106***,0.106***,0.170***
,(0.043),(0.037),(0.068),(0.029),(0.029),(0.046)
Treatment:Threshold,0.118***,0.118***,0.118***,0.181***,0.181***,0.181***
,(0.034),(0.033),(0.031),(0.030),(0.030),(0.027)
Time Delta,-0.005,-0.004,-0.015*,-0.005**,-0.005**,-0.015**
,(0.003),(0.002),(0.007),(0.002),(0.002),(0.005)
Treatment,0.031*,0.031**,0.031*,0.038**,0.038**,0.038***
,(0.014),(0.010),(0.014),(0.012),(0.012),(0.011)
Weekday,0.015***,0.016***,0.017***,0.015***,0.015***,0.016***
,(0.004),(0.004),(0.004),(0.003),(0.003),(0.003)
High SE class,,,,0.004,0.004,0.004
,,,,(0.009),(0.009),(0.008)
High SE class:Threshold,,,,-0.002,-0.002,-0.002
,,,,(0.013),(0.013),(0.014)
High SE class:Treatment,,,,-0.014,-0.014,-0.014
,,,,(0.014),(0.014),(0.012)
High SE class:Treatment:Threshold,,,,-0.097**,-0.097**,-0.097**
,,,,(0.037),(0.037),(0.034)
Medium SE class,,,,-0.003,-0.003,-0.003
,,,,(0.008),(0.008),(0.007)
Medium SE class:Threshold,,,,0.002,0.002,0.002
,,,,(0.012),(0.012),(0.013)
Medium SE class:Treatment,,,,-0.005,-0.005,-0.005
,,,,(0.012),(0.012),(0.012)
Medium SE class:Treatment:Threshold,,,,-0.072*,-0.072*,-0.072*
,,,,(0.033),(0.033),(0.031)
Time Delta ** 2,,-$<$0.001,-$<$0.001,,,-$<$0.001**
,,($<$0.001),($<$0.001),,,($<$0.001)
Time Delta ** 3,,,$<$0.001*,,,$<$0.001**
,,,($<$0.001),,,($<$0.001)
R-squared,0.666,0.685,0.733,0.663,0.663,0.721
Adjusted R-squared,0.637,0.652,0.699,0.639,0.639,0.697
No. observations,64,64,64,192,192,192

In [13]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 0.006 & 0.024 & -0.015 & 0.005 & 0.005 & -0.014 \\
  & (0.033) & (0.022) & (0.037) & (0.021) & (0.021) & (0.025) \\
Threshold & 0.103* & 0.094* & 0.169* & 0.106*** & 0.106*** & 0.170*** \\
  & (0.043) & (0.037) & (0.068) & (0.029) & (0.029) & (0.046) \\
Treatment:Threshold & 0.118*** & 0.118*** & 0.118*** & 0.181*** & 0.181*** & 0.181*** \\
  & (0.034) & (0.033) & (0.031) & (0.030) & (0.030) & (0.027) \\
Time Delta & -0.005 & -0.004 & -0.015* & -0.005** & -0.005** & -0.015** \\
  & (0.003) & (0.002) & (0.007) & (0.002) & (0.002) & (0.005) \\
Treatment & 0.031* & 0.031** & 0.031* & 0.038** & 0.038** & 0.038*** \\
  & (0.014) & (0.010) & (0.014) & (0.012) & (0.012) & (0.011) \\
Weekday & 0.015*** & 0.016*** & 0.017*** & 0.015*** & 0.015*** & 0.016*** \\
  & (0.004) & (0.004) & (0.004) & (0.003) & (0.003) & (0.003) \\
High SE class &   &   &   & 0.004 & 0.004 & 0.004 \\
  &   &   &   & (0.009) & (0.009) & (0.008) \\
High SE class:Threshold &   &   &   & -0.002 & -0.002 & -0.002 \\
  &   &   &   & (0.013) & (0.013) & (0.014) \\
High SE class:Treatment &   &   &   & -0.014 & -0.014 & -0.014 \\
  &   &   &   & (0.014) & (0.014) & (0.012) \\
High SE class:Treatment:Threshold &   &   &   & -0.097** & -0.097** & -0.097** \\
  &   &   &   & (0.037) & (0.037) & (0.034) \\
Medium SE class &   &   &   & -0.003 & -0.003 & -0.003 \\
  &   &   &   & (0.008) & (0.008) & (0.007) \\
Medium SE class:Threshold &   &   &   & 0.002 & 0.002 & 0.002 \\
  &   &   &   & (0.012) & (0.012) & (0.013) \\
Medium SE class:Treatment &   &   &   & -0.005 & -0.005 & -0.005 \\
  &   &   &   & (0.012) & (0.012) & (0.012) \\
Medium SE class:Treatment:Threshold &   &   &   & -0.072* & -0.072* & -0.072* \\
  &   &   &   & (0.033) & (0.033) & (0.031) \\
Time Delta ** 2 &   & -$<$0.001 & -$<$0.001 &   &   & -$<$0.001** \\
  &   & ($<$0.001) & ($<$0.001) &   &   & ($<$0.001) \\
Time Delta ** 3 &   &   & $<$0.001* &   &   & $<$0.001** \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.666 & 0.685 & 0.733 & 0.663 & 0.663 & 0.721 \\
Adjusted R-squared & 0.637 & 0.652 & 0.699 & 0.639 & 0.639 & 0.697 \\
No. observations & 64 & 64 & 64 & 192 & 192 & 192 \\
\bottomrule
\end{tabular}

In [14]:
regression_table1 = pd.read_csv('../data_created/regression_results/rdd_table1_median.csv')
regression_table1 = regression_table1.fillna(' ')

In [15]:
regression_table1 = pd.concat([regression_table1.iloc[16:18, :], regression_table1.iloc[28:34, :],
                               regression_table1.iloc[20:28, :], regression_table1.iloc[0:16, :],
                               regression_table1.iloc[34:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [16]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [17]:
regression_table1

,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
Variables,,,,,,
Intercept,4.013***,4.000***,4.258***,3.938***,3.928***,4.135***
,(0.171),(0.172),(0.161),(0.149),(0.157),(0.155)
Threshold,-0.418*,-0.420*,-0.722***,-0.596***,-0.598***,-0.839***
,(0.171),(0.173),(0.206),(0.155),(0.156),(0.191)
Time Delta,-0.021,-0.027,0.044,-0.022,-0.027,0.030
,(0.018),(0.039),(0.051),(0.012),(0.032),(0.036)
Time Delta:Threshold,0.039,0.053,-0.005,0.047**,0.057,0.011
,(0.022),(0.084),(0.091),(0.017),(0.069),(0.069)
High SE class,,,,-0.190,-0.190,-0.190
,,,,(0.115),(0.115),(0.113)
High SE class:Threshold,,,,0.127,0.127,0.127
,,,,(0.167),(0.167),(0.165)
Medium SE class,,,,0.339***,0.339***,0.339***
,,,,(0.083),(0.084),(0.078)
Medium SE class:Threshold,,,,0.403*,0.403*,0.403*
,,,,(0.162),(0.162),(0.159)
Tuesday,-1.359***,-1.364***,-1.393***,-1.336***,-1.340***,-1.363***
,(0.129),(0.130),(0.125),(0.127),(0.129),(0.128)
Wednesday,-1.450***,-1.456***,-1.490***,-1.501***,-1.506***,-1.533***
,(0.156),(0.156),(0.141),(0.146),(0.148),(0.143)
Thursday,-1.395***,-1.401***,-1.444***,-1.378***,-1.382***,-1.417***
,(0.137),(0.137),(0.123),(0.139),(0.140),(0.136)
Friday,-1.275***,-1.279***,-1.335***,-1.221***,-1.224***,-1.269***
,(0.109),(0.115),(0.092),(0.118),(0.120),(0.114)
Saturday,-0.749***,-0.747***,-0.783***,-0.739***,-0.738***,-0.767***
,(0.138),(0.142),(0.157),(0.140),(0.142),(0.149)
Sunday,-0.326*,-0.326*,-0.342*,-0.317*,-0.316*,-0.329*
,(0.146),(0.145),(0.140),(0.161),(0.160),(0.158)
Time Delta ** 2,,-$<$0.001,0.002,,-$<$0.001,0.001
,,(0.003),(0.003),,(0.002),(0.002)
Time Delta ** 3,,,-$<$0.001*,,,-$<$0.001
,,,($<$0.001),,,($<$0.001)
R-squared,0.871,0.871,0.885,0.805,0.805,0.811
Adjusted R-squared,0.816,0.807,0.819,0.773,0.770,0.775
No. observations,31,31,31,93,93,93

In [18]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 4.013*** & 4.000*** & 4.258*** & 3.938*** & 3.928*** & 4.135*** \\
  & (0.171) & (0.172) & (0.161) & (0.149) & (0.157) & (0.155) \\
Threshold & -0.418* & -0.420* & -0.722*** & -0.596*** & -0.598*** & -0.839*** \\
  & (0.171) & (0.173) & (0.206) & (0.155) & (0.156) & (0.191) \\
Time Delta & -0.021 & -0.027 & 0.044 & -0.022 & -0.027 & 0.030 \\
  & (0.018) & (0.039) & (0.051) & (0.012) & (0.032) & (0.036) \\
Time Delta:Threshold & 0.039 & 0.053 & -0.005 & 0.047** & 0.057 & 0.011 \\
  & (0.022) & (0.084) & (0.091) & (0.017) & (0.069) & (0.069) \\
High SE class &   &   &   & -0.190 & -0.190 & -0.190 \\
  &   &   &   & (0.115) & (0.115) & (0.113) \\
High SE class:Threshold &   &   &   & 0.127 & 0.127 & 0.127 \\
  &   &   &   & (0.167) & (0.167) & (0.165) \\
Medium SE class &   &   &   & 0.339*** & 0.339*** & 0.339*** \\
  &   &   &   & (0.083) & (0.084) & (0.078) \\
Medium SE class:Threshold &   &   &   & 0.403* & 0.403* & 0.403* \\
  &   &   &   & (0.162) & (0.162) & (0.159) \\
Tuesday & -1.359*** & -1.364*** & -1.393*** & -1.336*** & -1.340*** & -1.363*** \\
  & (0.129) & (0.130) & (0.125) & (0.127) & (0.129) & (0.128) \\
Wednesday & -1.450*** & -1.456*** & -1.490*** & -1.501*** & -1.506*** & -1.533*** \\
  & (0.156) & (0.156) & (0.141) & (0.146) & (0.148) & (0.143) \\
Thursday & -1.395*** & -1.401*** & -1.444*** & -1.378*** & -1.382*** & -1.417*** \\
  & (0.137) & (0.137) & (0.123) & (0.139) & (0.140) & (0.136) \\
Friday & -1.275*** & -1.279*** & -1.335*** & -1.221*** & -1.224*** & -1.269*** \\
  & (0.109) & (0.115) & (0.092) & (0.118) & (0.120) & (0.114) \\
Saturday & -0.749*** & -0.747*** & -0.783*** & -0.739*** & -0.738*** & -0.767*** \\
  & (0.138) & (0.142) & (0.157) & (0.140) & (0.142) & (0.149) \\
Sunday & -0.326* & -0.326* & -0.342* & -0.317* & -0.316* & -0.329* \\
  & (0.146) & (0.145) & (0.140) & (0.161) & (0.160) & (0.158) \\
Time Delta ** 2 &   & -$<$0.001 & 0.002 &   & -$<$0.001 & 0.001 \\
  &   & (0.003) & (0.003) &   & (0.002) & (0.002) \\
Time Delta ** 3 &   &   & -$<$0.001* &   &   & -$<$0.001 \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.871 & 0.871 & 0.885 & 0.805 & 0.805 & 0.811 \\
Adjusted R-squared & 0.816 & 0.807 & 0.819 & 0.773 & 0.770 & 0.775 \\
No. observations & 31 & 31 & 31 & 93 & 93 & 93 \\
\bottomrule
\end{tabular}

In [19]:
regression_table1 = pd.read_csv('../data_created/regression_results/did_table1_mean.csv')
regression_table1 = regression_table1.fillna(' ')

In [20]:
regression_table1

,Unnamed: 0,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
0,C(weekday)[T.1],-2.959***,-2.959***,-2.921***,-2.984***,-2.984***,-2.947***
1,,(0.386),(0.386),(0.345),(0.350),(0.350),(0.301)
2,C(weekday)[T.2],-4.569***,-4.569***,-4.519***,-4.564***,-4.564***,-4.515***
3,,(0.355),(0.354),(0.297),(0.338),(0.338),(0.310)
4,C(weekday)[T.3],-4.810***,-4.810***,-4.760***,-4.835***,-4.835***,-4.786***
5,,(0.455),(0.456),(0.407),(0.382),(0.383),(0.351)
6,C(weekday)[T.4],-3.899***,-3.899***,-3.857***,-3.900***,-3.900***,-3.859***
7,,(0.320),(0.320),(0.273),(0.289),(0.289),(0.262)
8,C(weekday)[T.5],-1.475***,-1.475***,-1.629***,-1.470***,-1.470***,-1.624***
9,,(0.435),(0.431),(0.328),(0.372),(0.370),(0.298)
10,C(weekday)[T.6],-2.018***,-2.018***,-2.090***,-2.007***,-2.007***,-2.079***
11,,(0.340),(0.340),(0.293),(0.347),(0.348),(0.295)
12,I(time_delta ** 2),,,0.007***,,,0.007***
13,,,,(0.001),,,(0.001)
14,I(time_delta ** 3),,,-0.001***,,,-0.001***
15,,,,(0.000),,,(0.000)
16,Intercept,14.855***,14.805***,14.624***,15.332***,15.286***,15.107***
17,,(0.360),(0.419),(0.420),(0.370),(0.386),(0.385)
18,R-squared,0.865,0.865,0.915,0.785,0.785,0.825
19,R-squared Adj.,0.838,0.835,0.892,0.762,0.761,0.803
20,quantile_pop_bins_percent_bachelor_home[T.High],,,,-0.984**,-0.984**,-0.984***
21,,,,,(0.311),(0.308),(0.278)
22,quantile_pop_bins_percent_bachelor_home[T.High...,,,,0.536,0.536,0.536
23,,,,,(0.481),(0.480),(0.458)
24,quantile_pop_bins_percent_bachelor_home[T.High...,,,,2.257***,2.257***,2.257***
25,,,,,(0.482),(0.482),(0.447)
26,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.422,-0.422,-0.422
27,,,,,(0.767),(0.767),(0.732)
28,quantile_pop_bins_percent_bachelor_home[T.Medium],,,,-0.348,-0.348,-0.348
29,,,,,(0.366),(0.363),(0.319)
30,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,0.572,0.572,0.572
31,,,,,(0.506),(0.505),(0.458)
32,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,1.714***,1.714***,1.714***
33,,,,,(0.450),(0.450),(0.381)
34,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,0.515,0.515,0.515
35,,,,,(0.733),(0.733),(0.674)
36,threshold,-1.071,-0.968,-1.560**,-1.445**,-1.350*,-1.942***
37,,(0.579),(0.704),(0.532),(0.534),(0.580),(0.554)
38,threshold:treatment,-1.205*,-1.413,-1.413,-1.142*,-1.332,-1.332
39,,(0.473),(1.238),(0.798),(0.524),(0.865),(0.705)
40,time_delta,0.084**,0.077*,0.193***,0.084***,0.078**,0.194***
41,,(0.031),(0.038),(0.042),(0.024),(0.027),(0.045)
42,time_delta:treatment,,0.013,0.013,,0.012,0.012
43,,,(0.063),(0.036),,(0.046),(0.034)
44,treatment,-1.766***,-1.666**,-1.666***,-3.207***,-3.115***,-3.115***
45,,(0.332),(0.563),(0.388),(0.352),(0.459),(0.355)
46,R-squared,0.865,0.865,0.915,0.785,0.785,0.825
47,Adjusted R-squared,0.838,0.835,0.892,0.762,0.761,0.803
48,No. observations,62,62,62,186,186,186

In [21]:
regression_table1 = pd.concat([regression_table1.iloc[16:18, :], regression_table1.iloc[36:46, :],
                               regression_table1.iloc[20:36, :], regression_table1.iloc[0:16, :],
                               regression_table1.iloc[46:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [22]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [23]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 14.855*** & 14.805*** & 14.624*** & 15.332*** & 15.286*** & 15.107*** \\
  & (0.360) & (0.419) & (0.420) & (0.370) & (0.386) & (0.385) \\
Threshold & -1.071 & -0.968 & -1.560** & -1.445** & -1.350* & -1.942*** \\
  & (0.579) & (0.704) & (0.532) & (0.534) & (0.580) & (0.554) \\
Treatment:Threshold & -1.205* & -1.413 & -1.413 & -1.142* & -1.332 & -1.332 \\
  & (0.473) & (1.238) & (0.798) & (0.524) & (0.865) & (0.705) \\
Time Delta & 0.084** & 0.077* & 0.193*** & 0.084*** & 0.078** & 0.194*** \\
  & (0.031) & (0.038) & (0.042) & (0.024) & (0.027) & (0.045) \\
Time Delta:Treatment &   & 0.013 & 0.013 &   & 0.012 & 0.012 \\
  &   & (0.063) & (0.036) &   & (0.046) & (0.034) \\
Treatment & -1.766*** & -1.666** & -1.666*** & -3.207*** & -3.115*** & -3.115*** \\
  & (0.332) & (0.563) & (0.388) & (0.352) & (0.459) & (0.355) \\
High SE class &   &   &   & -0.984** & -0.984** & -0.984*** \\
  &   &   &   & (0.311) & (0.308) & (0.278) \\
High SE class:Threshold &   &   &   & 0.536 & 0.536 & 0.536 \\
  &   &   &   & (0.481) & (0.480) & (0.458) \\
High SE class:Treatment &   &   &   & 2.257*** & 2.257*** & 2.257*** \\
  &   &   &   & (0.482) & (0.482) & (0.447) \\
High SE class:Treatment:Threshold &   &   &   & -0.422 & -0.422 & -0.422 \\
  &   &   &   & (0.767) & (0.767) & (0.732) \\
Medium SE class &   &   &   & -0.348 & -0.348 & -0.348 \\
  &   &   &   & (0.366) & (0.363) & (0.319) \\
Medium SE class:Threshold &   &   &   & 0.572 & 0.572 & 0.572 \\
  &   &   &   & (0.506) & (0.505) & (0.458) \\
Medium SE class:Treatment &   &   &   & 1.714*** & 1.714*** & 1.714*** \\
  &   &   &   & (0.450) & (0.450) & (0.381) \\
Medium SE class:Treatment:Threshold &   &   &   & 0.515 & 0.515 & 0.515 \\
  &   &   &   & (0.733) & (0.733) & (0.674) \\
Tuesday & -2.959*** & -2.959*** & -2.921*** & -2.984*** & -2.984*** & -2.947*** \\
  & (0.386) & (0.386) & (0.345) & (0.350) & (0.350) & (0.301) \\
Wednesday & -4.569*** & -4.569*** & -4.519*** & -4.564*** & -4.564*** & -4.515*** \\
  & (0.355) & (0.354) & (0.297) & (0.338) & (0.338) & (0.310) \\
Thursday & -4.810*** & -4.810*** & -4.760*** & -4.835*** & -4.835*** & -4.786*** \\
  & (0.455) & (0.456) & (0.407) & (0.382) & (0.383) & (0.351) \\
Friday & -3.899*** & -3.899*** & -3.857*** & -3.900*** & -3.900*** & -3.859*** \\
  & (0.320) & (0.320) & (0.273) & (0.289) & (0.289) & (0.262) \\
Saturday & -1.475*** & -1.475*** & -1.629*** & -1.470*** & -1.470*** & -1.624*** \\
  & (0.435) & (0.431) & (0.328) & (0.372) & (0.370) & (0.298) \\
Sunday & -2.018*** & -2.018*** & -2.090*** & -2.007*** & -2.007*** & -2.079*** \\
  & (0.340) & (0.340) & (0.293) & (0.347) & (0.348) & (0.295) \\
Time Delta ** 2 &   &   & 0.007*** &   &   & 0.007*** \\
  &   &   & (0.001) &   &   & (0.001) \\
Time Delta ** 3 &   &   & -0.001*** &   &   & -0.001*** \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.865 & 0.865 & 0.915 & 0.785 & 0.785 & 0.825 \\
Adjusted R-squared & 0.838 & 0.835 & 0.892 & 0.762 & 0.761 & 0.803 \\
No. observations & 62 & 62 & 62 & 186 & 186 & 186 \\
\bottomrule
\end{tabular}

In [24]:
regression_table1 = pd.read_csv('../data_created/regression_results/rdd_table_assortativity_all.csv')
regression_table1 = regression_table1.fillna(' ')

In [25]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[8:18, :],
                               regression_table1.iloc[0:4, :],
                               regression_table1.iloc[18:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [26]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [27]:
regression_table1

                              Model 1     Model 2      Model 3
Variables
Intercept                    0.951***    0.898***     0.940***
                              (0.014)     (0.026)      (0.015)
First Night (2-3 February)  -0.273***   -0.217***    -0.187***
                              (0.055)     (0.060)      (0.056)
Threshold                   -0.165***   -0.172***    -0.240***
                              (0.046)     (0.041)      (0.049)
Time Delta                     -0.001     -0.019*       -0.008
                              (0.001)     (0.008)      (0.004)
Time Delta:Threshold           0.010*      0.047*      0.042**
                              (0.005)     (0.019)      (0.013)
Weekday                      -0.014**   -0.013***    -0.014***
                              (0.004)     (0.004)      (0.003)
Time Delta ** 2                           -0.001*     -0.001**
                                       ($<$0.001)   ($<$0.001)
Time Delta ** 3                                    -$<$0.001**
                                                    ($<$0.001)
R-squared                       0.864       0.901        0.925
Adjusted R-squared              0.838       0.877        0.903
No. observations                   32          32           32

In [28]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 \\
Variables &  &  &  \\
\midrule
Intercept & 0.951*** & 0.898*** & 0.940*** \\
  & (0.014) & (0.026) & (0.015) \\
First Night (2-3 February) & -0.273*** & -0.217*** & -0.187*** \\
  & (0.055) & (0.060) & (0.056) \\
Threshold & -0.165*** & -0.172*** & -0.240*** \\
  & (0.046) & (0.041) & (0.049) \\
Time Delta & -0.001 & -0.019* & -0.008 \\
  & (0.001) & (0.008) & (0.004) \\
Time Delta:Threshold & 0.010* & 0.047* & 0.042** \\
  & (0.005) & (0.019) & (0.013) \\
Weekday & -0.014** & -0.013*** & -0.014*** \\
  & (0.004) & (0.004) & (0.003) \\
Time Delta ** 2 &   & -0.001* & -0.001** \\
  &   & ($<$0.001) & ($<$0.001) \\
Time Delta ** 3 &   &   & -$<$0.001** \\
  &   &   & ($<$0.001) \\
R-squared & 0.864 & 0.901 & 0.925 \\
Adjusted R-squared & 0.838 & 0.877 & 0.903 \\
No. observations & 32 & 32 & 32 \\
\bottomrule
\end{tabular}

In [29]:
regression_table1 = pd.read_csv('../data_created/regression_results/did_table_assortativity_all.csv')
regression_table1 = regression_table1.fillna(' ')

In [30]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[8:24, :],
                               regression_table1.iloc[0:4, :],
                               regression_table1.iloc[24:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [31]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [32]:
regression_table1

                              Model 1     Model 2     Model 3
Variables
Intercept                    1.003***    0.984***    0.997***
                              (0.020)     (0.009)     (0.017)
First Night (2-3 February)     -0.003   -0.023***       0.010
                              (0.018)     (0.006)     (0.024)
First Night:Treatment       -0.340***   -0.298***   -0.298***
                              (0.018)     (0.039)     (0.034)
Threshold                      -0.049      -0.008      -0.050
                              (0.027)     (0.009)     (0.029)
Treatment:Threshold         -0.083***    -0.164**    -0.164**
                              (0.020)     (0.064)     (0.056)
Time Delta                      0.002   -$<$0.001       0.005
                              (0.002)  ($<$0.001)     (0.003)
Time Delta:Treatment                        0.005       0.005
                                          (0.003)     (0.003)
Treatment                   -0.042***      -0.003      -0.003
                              (0.008)     (0.026)     (0.023)
Weekday                     -0.009***   -0.009***   -0.010***
                              (0.002)     (0.002)     (0.003)
Time Delta ** 2                                      $<$0.001
                                                   ($<$0.001)
Time Delta ** 3                                     -$<$0.001
                                                   ($<$0.001)
R-squared                       0.850       0.865       0.887
Adjusted R-squared              0.832       0.846       0.866
No. observations                   64          64          64

In [33]:
print(regression_table1.to_latex(na_rep='', column_format='lccc', escape=False))

\begin{tabular}{lccc}
\toprule
 & Model 1 & Model 2 & Model 3 \\
Variables &  &  &  \\
\midrule
Intercept & 1.003*** & 0.984*** & 0.997*** \\
  & (0.020) & (0.009) & (0.017) \\
First Night (2-3 February) & -0.003 & -0.023*** & 0.010 \\
  & (0.018) & (0.006) & (0.024) \\
First Night:Treatment & -0.340*** & -0.298*** & -0.298*** \\
  & (0.018) & (0.039) & (0.034) \\
Threshold & -0.049 & -0.008 & -0.050 \\
  & (0.027) & (0.009) & (0.029) \\
Treatment:Threshold & -0.083*** & -0.164** & -0.164** \\
  & (0.020) & (0.064) & (0.056) \\
Time Delta & 0.002 & -$<$0.001 & 0.005 \\
  & (0.002) & ($<$0.001) & (0.003) \\
Time Delta:Treatment &   & 0.005 & 0.005 \\
  &   & (0.003) & (0.003) \\
Treatment & -0.042*** & -0.003 & -0.003 \\
  & (0.008) & (0.026) & (0.023) \\
Weekday & -0.009*** & -0.009*** & -0.010*** \\
  & (0.002) & (0.002) & (0.003) \\
Time Delta ** 2 &   &   & $<$0.001 \\
  &   &   & ($<$0.001) \\
Time Delta ** 3 &   &   & -$<$0.001 \\
  &   &   & ($<$0.001) \\
R-squared & 0.850 & 0.865 & 0.887 \\
Adjusted R-squared & 0.832 & 0.846 & 0.866 \\
No. observations & 64 & 64 & 64 \\
\bottomrule
\end{tabular}