In [1]:
import pandas as pd
import re

In [2]:
# Renaming dictionary
renaming_dict = {
    'Intercept': 'Intercept',
    'threshold': 'Threshold',
    'time_delta': 'Time Delta',
    'time_delta:threshold': 'Time Delta:Threshold',
    'weekday': 'Weekday',
    'quantile_pop_bins_percent_bachelor_home[T.High]': 'High SE class',
    'quantile_pop_bins_percent_bachelor_home[T.High]:threshold': 'High SE class:Threshold',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]': 'Medium SE class',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]:threshold': 'Medium SE class:Threshold',
    'I(time_delta ** 2)':'Time Delta ** 2',
    'I(time_delta ** 3)':'Time Delta ** 3',
    'treatment':'Treatment',
    'threshold:treatment':'Treatment:Threshold',
    'C(weekday)[T.1]':'Tuesday',
    'C(weekday)[T.2]':'Wednesday',
    'C(weekday)[T.3]':'Thursday',
    'C(weekday)[T.4]':'Friday',
    'C(weekday)[T.5]':'Saturday',
    'C(weekday)[T.6]':'Sunday',
    'time_delta:treatment':'Time Delta:Treatment',
    'first_day':'First Night (2-3 February)',
    'first_day:treatment': 'First Night:Treatment',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]:treatment':'Medium SE class:Treatment',
    'quantile_pop_bins_percent_bachelor_home[T.High]:treatment':'High SE class:Treatment',
    'quantile_pop_bins_percent_bachelor_home[T.Medium]:treatment:threshold':'Medium SE class:Treat:Thres',
    'quantile_pop_bins_percent_bachelor_home[T.High]:treatment:threshold':'High SE class:Treat:Thres'
}

# Function to rename variables
def rename_variables(df, renaming_dict):
    df_renamed = df.rename(index=renaming_dict)
    return df_renamed


def modify_zeros(df):
    # Define a function to apply to each cell
    def replace_zero(value):
        if isinstance(value, str):
            return re.sub(r'\b0\.000(\*+)?\b', r'$<$0.001\1', value)
        return value
        
    modified_df = df.map(replace_zero)
    
    return modified_df

\textit{Notes:} Standard Errors are in parentheses. Standard Errors are heteroscedasticity and autocorrelation robust (HAC) using 1 lag. 

    *** p$<$0.001, ** p$<$0.01, * p$<$0.05.

In [3]:
regression_table1 = pd.read_csv('../data_created/regression_results/rdd_table1.csv')
regression_table1 = regression_table1.fillna(' ')

In [4]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[16:24, :],
                               regression_table1.iloc[8:16, :], regression_table1.iloc[0:4, :],
                               regression_table1.iloc[24:27, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [5]:
regression_table1 = rename_variables(regression_table1, renaming_dict)

In [6]:
regression_table1 = modify_zeros(regression_table1)

In [7]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 0.067*** & 0.165*** & 0.096*** & 0.075*** & 0.169*** & 0.102*** \\
  & (0.019) & (0.035) & (0.021) & (0.014) & (0.027) & (0.015) \\
Threshold & 0.269*** & 0.261*** & 0.353*** & 0.331*** & 0.323*** & 0.413*** \\
  & (0.064) & (0.054) & (0.051) & (0.038) & (0.031) & (0.033) \\
Time Delta & 0.001 & 0.033*** & 0.014* & 0.001 & 0.032*** & 0.013** \\
  & (0.002) & (0.009) & (0.005) & (0.001) & (0.007) & (0.004) \\
Time Delta:Threshold & -0.018** & -0.082*** & -0.069*** & -0.019*** & -0.080*** & -0.068*** \\
  & (0.006) & (0.019) & (0.013) & (0.004) & (0.015) & (0.010) \\
Weekday & 0.021*** & 0.018*** & 0.019*** & 0.020*** & 0.018*** & 0.019*** \\
  & (0.006) & (0.004) & (0.004) & (0.004) & (0.003) & (0.003) \\
High SE class &   &   &   & -0.010 & -0.010 & -0.010 \\
  &   &   &   & (0.009) & (0.013) & (0.008) \\
High SE class:Threshold &   &   &   & -0.086** & -0.086** & -0.086*** \\
  &   &   &   & (0.028) & (0.026) & (0.025) \\
Medium SE class &   &   &   & -0.007 & -0.007 & -0.007 \\
  &   &   &   & (0.007) & (0.011) & (0.007) \\
Medium SE class:Threshold &   &   &   & -0.058* & -0.058* & -0.058* \\
  &   &   &   & (0.026) & (0.024) & (0.023) \\
Time Delta ** 2 &   & 0.002*** & 0.002*** &   & 0.002*** & 0.002*** \\
  &   & (0.001) & ($<$0.001) &   & ($<$0.001) & ($<$0.001) \\
Time Delta ** 3 &   &   & $<$0.001*** &   &   & $<$0.001*** \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.754 & 0.855 & 0.899 & 0.739 & 0.818 & 0.853 \\
Adjusted R-squared & 0.718 & 0.828 & 0.874 & 0.715 & 0.799 & 0.835 \\
No. observations & 32 & 32 & 32 & 96 & 96 & 96 \\
\bottomrule
\end{tabular}

In [8]:
regression_table1 = pd.read_csv('../data_created/regression_results/did_table1.csv')
regression_table1 = regression_table1.fillna(' ')

In [9]:
regression_table1

,Unnamed: 0,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
0,I(time_delta ** 2),,-0.000,-0.000*,,,-0.000**
1,,,(0.000),(0.000),,,(0.000)
2,I(time_delta ** 3),,,0.000*,,,0.000**
3,,,,(0.000),,,(0.000)
4,Intercept,0.006,0.025,-0.014,0.005,0.005,-0.013
5,,(0.033),(0.023),(0.038),(0.022),(0.022),(0.025)
6,R-squared,0.656,0.677,0.723,0.648,0.648,0.708
7,R-squared Adj.,0.626,0.643,0.689,0.622,0.622,0.683
8,quantile_pop_bins_percent_bachelor_home[T.High],,,,0.004,0.004,0.004
9,,,,,(0.009),(0.009),(0.008)
10,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.001,-0.001,-0.001
11,,,,,(0.013),(0.013),(0.014)
12,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.014,-0.014,-0.014
13,,,,,(0.014),(0.014),(0.012)
14,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.085*,-0.085*,-0.085*
15,,,,,(0.037),(0.037),(0.034)
16,quantile_pop_bins_percent_bachelor_home[T.Medium],,,,-0.003,-0.003,-0.003
17,,,,,(0.008),(0.008),(0.007)
18,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,-0.001,-0.001,-0.001
19,,,,,(0.012),(0.012),(0.014)
20,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,-0.005,-0.005,-0.005
21,,,,,(0.013),(0.013),(0.012)
22,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,-0.057,-0.057,-0.057
23,,,,,(0.034),(0.034),(0.031)
24,threshold,0.104*,0.095*,0.170*,0.109***,0.109***,0.172***
25,,(0.044),(0.038),(0.070),(0.030),(0.030),(0.047)
26,threshold:treatment,0.116***,0.116***,0.116***,0.169***,0.169***,0.169***
27,,(0.035),(0.034),(0.032),(0.030),(0.030),(0.027)
28,time_delta,-0.005,-0.004,-0.015*,-0.005**,-0.005**,-0.015**
29,,(0.003),(0.002),(0.007),(0.002),(0.002),(0.005)
30,treatment,0.031*,0.031**,0.031*,0.038**,0.038**,0.038***
31,,(0.014),(0.010),(0.014),(0.012),(0.012),(0.011)
32,weekday,0.015***,0.016***,0.016***,0.015***,0.015***,0.016***
33,,(0.004),(0.004),(0.004),(0.003),(0.003),(0.003)
34,R-squared,0.656,0.677,0.723,0.648,0.648,0.708
35,Adjusted R-squared,0.626,0.643,0.689,0.622,0.622,0.683
36,No. observations,64,64,64,192,192,192

In [10]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[24:34, :],
                               regression_table1.iloc[8:24, :], regression_table1.iloc[0:4, :],
                               regression_table1.iloc[34:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [11]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [12]:
regression_table1

,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
Variables,,,,,,
Intercept,0.006,0.025,-0.014,0.005,0.005,-0.013
,(0.033),(0.023),(0.038),(0.022),(0.022),(0.025)
Threshold,0.104*,0.095*,0.170*,0.109***,0.109***,0.172***
,(0.044),(0.038),(0.070),(0.030),(0.030),(0.047)
Treatment:Threshold,0.116***,0.116***,0.116***,0.169***,0.169***,0.169***
,(0.035),(0.034),(0.032),(0.030),(0.030),(0.027)
Time Delta,-0.005,-0.004,-0.015*,-0.005**,-0.005**,-0.015**
,(0.003),(0.002),(0.007),(0.002),(0.002),(0.005)
Treatment,0.031*,0.031**,0.031*,0.038**,0.038**,0.038***
,(0.014),(0.010),(0.014),(0.012),(0.012),(0.011)
Weekday,0.015***,0.016***,0.016***,0.015***,0.015***,0.016***
,(0.004),(0.004),(0.004),(0.003),(0.003),(0.003)
High SE class,,,,0.004,0.004,0.004
,,,,(0.009),(0.009),(0.008)
High SE class:Threshold,,,,-0.001,-0.001,-0.001
,,,,(0.013),(0.013),(0.014)
High SE class:Treatment,,,,-0.014,-0.014,-0.014
,,,,(0.014),(0.014),(0.012)
High SE class:Treat:Thres,,,,-0.085*,-0.085*,-0.085*
,,,,(0.037),(0.037),(0.034)
Medium SE class,,,,-0.003,-0.003,-0.003
,,,,(0.008),(0.008),(0.007)
Medium SE class:Threshold,,,,-0.001,-0.001,-0.001
,,,,(0.012),(0.012),(0.014)
Medium SE class:Treatment,,,,-0.005,-0.005,-0.005
,,,,(0.013),(0.013),(0.012)
Medium SE class:Treat:Thres,,,,-0.057,-0.057,-0.057
,,,,(0.034),(0.034),(0.031)
Time Delta ** 2,,-$<$0.001,-$<$0.001*,,,-$<$0.001**
,,($<$0.001),($<$0.001),,,($<$0.001)
Time Delta ** 3,,,$<$0.001*,,,$<$0.001**
,,,($<$0.001),,,($<$0.001)
R-squared,0.656,0.677,0.723,0.648,0.648,0.708
Adjusted R-squared,0.626,0.643,0.689,0.622,0.622,0.683
No. observations,64,64,64,192,192,192

In [13]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 0.006 & 0.025 & -0.014 & 0.005 & 0.005 & -0.013 \\
  & (0.033) & (0.023) & (0.038) & (0.022) & (0.022) & (0.025) \\
Threshold & 0.104* & 0.095* & 0.170* & 0.109*** & 0.109*** & 0.172*** \\
  & (0.044) & (0.038) & (0.070) & (0.030) & (0.030) & (0.047) \\
Treatment:Threshold & 0.116*** & 0.116*** & 0.116*** & 0.169*** & 0.169*** & 0.169*** \\
  & (0.035) & (0.034) & (0.032) & (0.030) & (0.030) & (0.027) \\
Time Delta & -0.005 & -0.004 & -0.015* & -0.005** & -0.005** & -0.015** \\
  & (0.003) & (0.002) & (0.007) & (0.002) & (0.002) & (0.005) \\
Treatment & 0.031* & 0.031** & 0.031* & 0.038** & 0.038** & 0.038*** \\
  & (0.014) & (0.010) & (0.014) & (0.012) & (0.012) & (0.011) \\
Weekday & 0.015*** & 0.016*** & 0.016*** & 0.015*** & 0.015*** & 0.016*** \\
  & (0.004) & (0.004) & (0.004) & (0.003) & (0.003) & (0.003) \\
High SE class &   &   &   & 0.004 & 0.004 & 0.004 \\
  &   &   &   & (0.009) & (0.009) & (0.008) \\
High SE class:Threshold &   &   &   & -0.001 & -0.001 & -0.001 \\
  &   &   &   & (0.013) & (0.013) & (0.014) \\
High SE class:Treatment &   &   &   & -0.014 & -0.014 & -0.014 \\
  &   &   &   & (0.014) & (0.014) & (0.012) \\
High SE class:Treat:Thres &   &   &   & -0.085* & -0.085* & -0.085* \\
  &   &   &   & (0.037) & (0.037) & (0.034) \\
Medium SE class &   &   &   & -0.003 & -0.003 & -0.003 \\
  &   &   &   & (0.008) & (0.008) & (0.007) \\
Medium SE class:Threshold &   &   &   & -0.001 & -0.001 & -0.001 \\
  &   &   &   & (0.012) & (0.012) & (0.014) \\
Medium SE class:Treatment &   &   &   & -0.005 & -0.005 & -0.005 \\
  &   &   &   & (0.013) & (0.013) & (0.012) \\
Medium SE class:Treat:Thres &   &   &   & -0.057 & -0.057 & -0.057 \\
  &   &   &   & (0.034) & (0.034) & (0.031) \\
Time Delta ** 2 &   & -$<$0.001 & -$<$0.001* &   &   & -$<$0.001** \\
  &   & ($<$0.001) & ($<$0.001) &   &   & ($<$0.001) \\
Time Delta ** 3 &   &   & $<$0.001* &   &   & $<$0.001** \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.656 & 0.677 & 0.723 & 0.648 & 0.648 & 0.708 \\
Adjusted R-squared & 0.626 & 0.643 & 0.689 & 0.622 & 0.622 & 0.683 \\
No. observations & 64 & 64 & 64 & 192 & 192 & 192 \\
\bottomrule
\end{tabular}

In [14]:
regression_table1 = pd.read_csv('../data_created/regression_results/rdd_table1_mean.csv')
regression_table1 = regression_table1.fillna(' ')

In [15]:
regression_table1 = pd.concat([regression_table1.iloc[16:18, :], regression_table1.iloc[28:34, :],
                               regression_table1.iloc[20:28, :], regression_table1.iloc[0:16, :],
                               regression_table1.iloc[34:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [16]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [17]:
regression_table1

,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
Variables,,,,,,
Intercept,11.215***,10.903***,11.566***,10.273***,9.972***,10.630***
,(0.519),(0.543),(0.647),(0.465),(0.557),(0.625)
Threshold,-1.637**,-1.701**,-2.474***,-1.760***,-1.821***,-2.589***
,(0.593),(0.540),(0.666),(0.474),(0.479),(0.659)
Time Delta,-0.081*,-0.233**,-0.051,-0.082*,-0.228,-0.048
,(0.036),(0.089),(0.125),(0.035),(0.117),(0.123)
Time Delta:Threshold,0.260***,0.581***,0.432*,0.258***,0.566*,0.418*
,(0.045),(0.160),(0.169),(0.050),(0.227),(0.204)
High SE class,,,,1.273***,1.273***,1.273***
,,,,(0.345),(0.346),(0.337)
High SE class:Threshold,,,,-0.143,-0.143,-0.143
,,,,(0.546),(0.544),(0.537)
Medium SE class,,,,1.366***,1.366***,1.366***
,,,,(0.225),(0.237),(0.213)
Medium SE class:Threshold,,,,0.830,0.830,0.830
,,,,(0.490),(0.496),(0.487)
Tuesday,-2.653***,-2.777***,-2.850***,-2.749***,-2.868***,-2.940***
,(0.536),(0.513),(0.516),(0.416),(0.401),(0.401)
Wednesday,-3.626***,-3.758***,-3.846***,-3.645***,-3.773***,-3.860***
,(0.405),(0.363),(0.371),(0.434),(0.412),(0.420)
Thursday,-3.437***,-3.557***,-3.669***,-3.525***,-3.641***,-3.752***
,(0.635),(0.578),(0.563),(0.533),(0.496),(0.488)
Friday,-2.928***,-3.014***,-3.157***,-2.938***,-3.021***,-3.163***
,(0.492),(0.494),(0.416),(0.416),(0.424),(0.383)
Saturday,-1.371**,-1.332***,-1.424***,-1.395***,-1.358***,-1.449***
,(0.434),(0.375),(0.377),(0.413),(0.382),(0.376)
Sunday,-1.263***,-1.254***,-1.296***,-1.261**,-1.253**,-1.295**
,(0.352),(0.327),(0.325),(0.441),(0.416),(0.408)
Time Delta ** 2,,-0.011*,-0.005,,-0.010,-0.005
,,(0.005),(0.005),,(0.007),(0.006)
Time Delta ** 3,,,-$<$0.001*,,,-$<$0.001*
,,,($<$0.001),,,($<$0.001)
R-squared,0.853,0.866,0.880,0.710,0.718,0.727
Adjusted R-squared,0.791,0.799,0.810,0.663,0.667,0.674
No. observations,31,31,31,93,93,93

In [18]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 11.215*** & 10.903*** & 11.566*** & 10.273*** & 9.972*** & 10.630*** \\
  & (0.519) & (0.543) & (0.647) & (0.465) & (0.557) & (0.625) \\
Threshold & -1.637** & -1.701** & -2.474*** & -1.760*** & -1.821*** & -2.589*** \\
  & (0.593) & (0.540) & (0.666) & (0.474) & (0.479) & (0.659) \\
Time Delta & -0.081* & -0.233** & -0.051 & -0.082* & -0.228 & -0.048 \\
  & (0.036) & (0.089) & (0.125) & (0.035) & (0.117) & (0.123) \\
Time Delta:Threshold & 0.260*** & 0.581*** & 0.432* & 0.258*** & 0.566* & 0.418* \\
  & (0.045) & (0.160) & (0.169) & (0.050) & (0.227) & (0.204) \\
High SE class &   &   &   & 1.273*** & 1.273*** & 1.273*** \\
  &   &   &   & (0.345) & (0.346) & (0.337) \\
High SE class:Threshold &   &   &   & -0.143 & -0.143 & -0.143 \\
  &   &   &   & (0.546) & (0.544) & (0.537) \\
Medium SE class &   &   &   & 1.366*** & 1.366*** & 1.366*** \\
  &   &   &   & (0.225) & (0.237) & (0.213) \\
Medium SE class:Threshold &   &   &   & 0.830 & 0.830 & 0.830 \\
  &   &   &   & (0.490) & (0.496) & (0.487) \\
Tuesday & -2.653*** & -2.777*** & -2.850*** & -2.749*** & -2.868*** & -2.940*** \\
  & (0.536) & (0.513) & (0.516) & (0.416) & (0.401) & (0.401) \\
Wednesday & -3.626*** & -3.758*** & -3.846*** & -3.645*** & -3.773*** & -3.860*** \\
  & (0.405) & (0.363) & (0.371) & (0.434) & (0.412) & (0.420) \\
Thursday & -3.437*** & -3.557*** & -3.669*** & -3.525*** & -3.641*** & -3.752*** \\
  & (0.635) & (0.578) & (0.563) & (0.533) & (0.496) & (0.488) \\
Friday & -2.928*** & -3.014*** & -3.157*** & -2.938*** & -3.021*** & -3.163*** \\
  & (0.492) & (0.494) & (0.416) & (0.416) & (0.424) & (0.383) \\
Saturday & -1.371** & -1.332*** & -1.424*** & -1.395*** & -1.358*** & -1.449*** \\
  & (0.434) & (0.375) & (0.377) & (0.413) & (0.382) & (0.376) \\
Sunday & -1.263*** & -1.254*** & -1.296*** & -1.261** & -1.253** & -1.295** \\
  & (0.352) & (0.327) & (0.325) & (0.441) & (0.416) & (0.408) \\
Time Delta ** 2 &   & -0.011* & -0.005 &   & -0.010 & -0.005 \\
  &   & (0.005) & (0.005) &   & (0.007) & (0.006) \\
Time Delta ** 3 &   &   & -$<$0.001* &   &   & -$<$0.001* \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.853 & 0.866 & 0.880 & 0.710 & 0.718 & 0.727 \\
Adjusted R-squared & 0.791 & 0.799 & 0.810 & 0.663 & 0.667 & 0.674 \\
No. observations & 31 & 31 & 31 & 93 & 93 & 93 \\
\bottomrule
\end{tabular}

In [19]:
regression_table1 = pd.read_csv('../data_created/regression_results/did_table1_mean.csv')
regression_table1 = regression_table1.fillna(' ')

In [20]:
regression_table1

,Unnamed: 0,Model 1,Model 2,Model 3,Model 4,Model 5,Model 6
0,C(weekday)[T.1],-2.949***,-2.949***,-2.895***,-2.975***,-2.975***,-2.922***
1,,(0.386),(0.386),(0.345),(0.346),(0.346),(0.297)
2,C(weekday)[T.2],-4.562***,-4.562***,-4.494***,-4.558***,-4.558***,-4.491***
3,,(0.355),(0.354),(0.298),(0.333),(0.333),(0.306)
4,C(weekday)[T.3],-4.708***,-4.708***,-4.638***,-4.754***,-4.754***,-4.685***
5,,(0.464),(0.468),(0.407),(0.383),(0.386),(0.349)
6,C(weekday)[T.4],-3.900***,-3.900***,-3.837***,-3.898***,-3.898***,-3.835***
7,,(0.316),(0.317),(0.277),(0.286),(0.285),(0.264)
8,C(weekday)[T.5],-1.329**,-1.329**,-1.478***,-1.325***,-1.325***,-1.471***
9,,(0.431),(0.418),(0.312),(0.366),(0.359),(0.290)
10,C(weekday)[T.6],-1.987***,-1.987***,-2.057***,-1.973***,-1.973***,-2.040***
11,,(0.333),(0.333),(0.286),(0.342),(0.342),(0.293)
12,I(time_delta ** 2),,,0.007***,,,0.007***
13,,,,(0.001),,,(0.001)
14,I(time_delta ** 3),,,-0.001***,,,-0.001***
15,,,,(0.000),,,(0.000)
16,Intercept,14.844***,14.712***,14.467***,15.310***,15.182***,14.941***
17,,(0.358),(0.403),(0.415),(0.366),(0.373),(0.384)
18,R-squared,0.866,0.868,0.918,0.785,0.786,0.825
19,R-squared Adj.,0.840,0.839,0.896,0.761,0.761,0.802
20,quantile_pop_bins_percent_bachelor_home[T.High],,,,-0.984**,-0.984**,-0.984***
21,,,,,(0.311),(0.303),(0.282)
22,quantile_pop_bins_percent_bachelor_home[T.High...,,,,0.532,0.532,0.532
23,,,,,(0.479),(0.476),(0.456)
24,quantile_pop_bins_percent_bachelor_home[T.High...,,,,2.257***,2.257***,2.257***
25,,,,,(0.484),(0.484),(0.451)
26,quantile_pop_bins_percent_bachelor_home[T.High...,,,,-0.675,-0.675,-0.675
27,,,,,(0.770),(0.769),(0.733)
28,quantile_pop_bins_percent_bachelor_home[T.Medium],,,,-0.348,-0.348,-0.348
29,,,,,(0.365),(0.355),(0.315)
30,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,0.719,0.719,0.719
31,,,,,(0.510),(0.507),(0.469)
32,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,1.714***,1.714***,1.714***
33,,,,,(0.449),(0.448),(0.378)
34,quantile_pop_bins_percent_bachelor_home[T.Medi...,,,,0.111,0.111,0.111
35,,,,,(0.737),(0.737),(0.680)
36,threshold,-1.095*,-0.821,-1.332**,-1.483**,-1.217*,-1.717**
37,,(0.556),(0.645),(0.501),(0.525),(0.556),(0.550)
38,threshold:treatment,-1.148*,-1.696,-1.696*,-0.890,-1.420,-1.420*
39,,(0.472),(1.208),(0.781),(0.529),(0.854),(0.700)
40,time_delta,0.088**,0.070*,0.176***,0.087***,0.069**,0.173***
41,,(0.030),(0.036),(0.040),(0.023),(0.025),(0.045)
42,time_delta:treatment,,0.035,0.035,,0.034,0.034
43,,,(0.061),(0.034),,(0.045),(0.033)
44,treatment,-1.766***,-1.501**,-1.501***,-3.207***,-2.950***,-2.950***
45,,(0.336),(0.560),(0.382),(0.353),(0.454),(0.354)
46,R-squared,0.866,0.868,0.918,0.785,0.786,0.825
47,Adjusted R-squared,0.840,0.839,0.896,0.761,0.761,0.802
48,No. observations,62,62,62,186,186,186

In [21]:
regression_table1 = pd.concat([regression_table1.iloc[16:18, :], regression_table1.iloc[36:46, :],
                               regression_table1.iloc[20:36, :], regression_table1.iloc[0:16, :],
                               regression_table1.iloc[46:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [22]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [23]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 & Model 6 \\
Variables &  &  &  &  &  &  \\
\midrule
Intercept & 14.844*** & 14.712*** & 14.467*** & 15.310*** & 15.182*** & 14.941*** \\
  & (0.358) & (0.403) & (0.415) & (0.366) & (0.373) & (0.384) \\
Threshold & -1.095* & -0.821 & -1.332** & -1.483** & -1.217* & -1.717** \\
  & (0.556) & (0.645) & (0.501) & (0.525) & (0.556) & (0.550) \\
Treatment:Threshold & -1.148* & -1.696 & -1.696* & -0.890 & -1.420 & -1.420* \\
  & (0.472) & (1.208) & (0.781) & (0.529) & (0.854) & (0.700) \\
Time Delta & 0.088** & 0.070* & 0.176*** & 0.087*** & 0.069** & 0.173*** \\
  & (0.030) & (0.036) & (0.040) & (0.023) & (0.025) & (0.045) \\
Time Delta:Treatment &   & 0.035 & 0.035 &   & 0.034 & 0.034 \\
  &   & (0.061) & (0.034) &   & (0.045) & (0.033) \\
Treatment & -1.766*** & -1.501** & -1.501*** & -3.207*** & -2.950*** & -2.950*** \\
  & (0.336) & (0.560) & (0.382) & (0.353) & (0.454) & (0.354) \\
High SE class &   &   &   & -0.984** & -0.984** & -0.984*** \\
  &   &   &   & (0.311) & (0.303) & (0.282) \\
High SE class:Threshold &   &   &   & 0.532 & 0.532 & 0.532 \\
  &   &   &   & (0.479) & (0.476) & (0.456) \\
High SE class:Treatment &   &   &   & 2.257*** & 2.257*** & 2.257*** \\
  &   &   &   & (0.484) & (0.484) & (0.451) \\
High SE class:Treat:Thres &   &   &   & -0.675 & -0.675 & -0.675 \\
  &   &   &   & (0.770) & (0.769) & (0.733) \\
Medium SE class &   &   &   & -0.348 & -0.348 & -0.348 \\
  &   &   &   & (0.365) & (0.355) & (0.315) \\
Medium SE class:Threshold &   &   &   & 0.719 & 0.719 & 0.719 \\
  &   &   &   & (0.510) & (0.507) & (0.469) \\
Medium SE class:Treatment &   &   &   & 1.714*** & 1.714*** & 1.714*** \\
  &   &   &   & (0.449) & (0.448) & (0.378) \\
Medium SE class:Treat:Thres &   &   &   & 0.111 & 0.111 & 0.111 \\
  &   &   &   & (0.737) & (0.737) & (0.680) \\
Tuesday & -2.949*** & -2.949*** & -2.895*** & -2.975*** & -2.975*** & -2.922*** \\
  & (0.386) & (0.386) & (0.345) & (0.346) & (0.346) & (0.297) \\
Wednesday & -4.562*** & -4.562*** & -4.494*** & -4.558*** & -4.558*** & -4.491*** \\
  & (0.355) & (0.354) & (0.298) & (0.333) & (0.333) & (0.306) \\
Thursday & -4.708*** & -4.708*** & -4.638*** & -4.754*** & -4.754*** & -4.685*** \\
  & (0.464) & (0.468) & (0.407) & (0.383) & (0.386) & (0.349) \\
Friday & -3.900*** & -3.900*** & -3.837*** & -3.898*** & -3.898*** & -3.835*** \\
  & (0.316) & (0.317) & (0.277) & (0.286) & (0.285) & (0.264) \\
Saturday & -1.329** & -1.329** & -1.478*** & -1.325*** & -1.325*** & -1.471*** \\
  & (0.431) & (0.418) & (0.312) & (0.366) & (0.359) & (0.290) \\
Sunday & -1.987*** & -1.987*** & -2.057*** & -1.973*** & -1.973*** & -2.040*** \\
  & (0.333) & (0.333) & (0.286) & (0.342) & (0.342) & (0.293) \\
Time Delta ** 2 &   &   & 0.007*** &   &   & 0.007*** \\
  &   &   & (0.001) &   &   & (0.001) \\
Time Delta ** 3 &   &   & -0.001*** &   &   & -0.001*** \\
  &   &   & ($<$0.001) &   &   & ($<$0.001) \\
R-squared & 0.866 & 0.868 & 0.918 & 0.785 & 0.786 & 0.825 \\
Adjusted R-squared & 0.840 & 0.839 & 0.896 & 0.761 & 0.761 & 0.802 \\
No. observations & 62 & 62 & 62 & 186 & 186 & 186 \\
\bottomrule
\end{tabular}

In [24]:
regression_table1 = pd.read_csv('../data_created/regression_results/rdd_table_assortativity_moved.csv')
regression_table1 = regression_table1.fillna(' ')

In [25]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[8:18, :],
                               regression_table1.iloc[0:4, :],
                               regression_table1.iloc[18:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [26]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [27]:
regression_table1

                              Model 1     Model 2     Model 3
Variables
Intercept                    0.233***    0.247***    0.273***
                              (0.021)     (0.025)     (0.018)
First Night (2-3 February)  -0.236***   -0.251***   -0.232***
                              (0.025)     (0.035)     (0.034)
Threshold                    0.108***    0.110***      0.067*
                              (0.030)     (0.029)     (0.031)
Time Delta                     -0.003       0.002       0.009
                              (0.002)     (0.007)     (0.005)
Time Delta:Threshold           -0.004      -0.014      -0.017
                              (0.003)     (0.015)     (0.012)
Weekday                       -0.008*    -0.008**    -0.009**
                              (0.003)     (0.003)     (0.003)
Time Delta ** 2                          $<$0.001    $<$0.001
                                       ($<$0.001)  ($<$0.001)
Time Delta ** 3                                     -$<$0.001
                                                   ($<$0.001)
R-squared                       0.604       0.612       0.642
Adjusted R-squared              0.528       0.519       0.538
No. observations                   32          32          32

In [28]:
print(regression_table1.to_latex(na_rep='', column_format='lcccccc', escape=False))

\begin{tabular}{lcccccc}
\toprule
 & Model 1 & Model 2 & Model 3 \\
Variables &  &  &  \\
\midrule
Intercept & 0.233*** & 0.247*** & 0.273*** \\
  & (0.021) & (0.025) & (0.018) \\
First Night (2-3 February) & -0.236*** & -0.251*** & -0.232*** \\
  & (0.025) & (0.035) & (0.034) \\
Threshold & 0.108*** & 0.110*** & 0.067* \\
  & (0.030) & (0.029) & (0.031) \\
Time Delta & -0.003 & 0.002 & 0.009 \\
  & (0.002) & (0.007) & (0.005) \\
Time Delta:Threshold & -0.004 & -0.014 & -0.017 \\
  & (0.003) & (0.015) & (0.012) \\
Weekday & -0.008* & -0.008** & -0.009** \\
  & (0.003) & (0.003) & (0.003) \\
Time Delta ** 2 &   & $<$0.001 & $<$0.001 \\
  &   & ($<$0.001) & ($<$0.001) \\
Time Delta ** 3 &   &   & -$<$0.001 \\
  &   &   & ($<$0.001) \\
R-squared & 0.604 & 0.612 & 0.642 \\
Adjusted R-squared & 0.528 & 0.519 & 0.538 \\
No. observations & 32 & 32 & 32 \\
\bottomrule
\end{tabular}

In [29]:
regression_table1 = pd.read_csv('../data_created/regression_results/did_table_assortativity_moved.csv')
regression_table1 = regression_table1.fillna(' ')

In [30]:
regression_table1 = pd.concat([regression_table1.iloc[4:6, :], regression_table1.iloc[8:24, :],
                               regression_table1.iloc[0:4, :],
                               regression_table1.iloc[24:, :]]).rename(columns={'Unnamed: 0':'Variables'}).set_index('Variables')

In [31]:
regression_table1 = rename_variables(regression_table1, renaming_dict)
regression_table1=modify_zeros(regression_table1)

In [32]:
regression_table1

                              Model 1    Model 2     Model 3
Variables
Intercept                    0.392***   0.413***    0.432***
                              (0.013)    (0.012)     (0.016)
First Night (2-3 February)  -0.053***  -0.031***      -0.024
                              (0.011)    (0.009)     (0.014)
First Night:Treatment       -0.143***  -0.188***   -0.188***
                              (0.014)    (0.021)     (0.019)
Threshold                       0.027     -0.016      -0.042
                              (0.021)    (0.018)     (0.024)
Treatment:Threshold            0.040*   0.127***    0.127***
                              (0.019)    (0.038)     (0.033)
Time Delta                    -0.002*   $<$0.001       0.004
                              (0.001)    (0.001)     (0.002)
Time Delta:Treatment                    -0.005**   -0.005***
                                         (0.002)     (0.002)
Treatment                   -0.155***  -0.198***   -0.198***
                              (0.012)    (0.021)     (0.017)
Weekday                     -0.008***  -0.008***   -0.008***
                              (0.002)    (0.002)     (0.002)
Time Delta ** 2                                    -$<$0.001
                                                  ($<$0.001)
Time Delta ** 3                                    -$<$0.001
                                                  ($<$0.001)
R-squared                       0.844      0.863       0.873
Adjusted R-squared              0.824      0.843       0.849
No. observations                   64         64          64

In [33]:
print(regression_table1.to_latex(na_rep='', column_format='lccc', escape=False))

\begin{tabular}{lccc}
\toprule
 & Model 1 & Model 2 & Model 3 \\
Variables &  &  &  \\
\midrule
Intercept & 0.392*** & 0.413*** & 0.432*** \\
  & (0.013) & (0.012) & (0.016) \\
First Night (2-3 February) & -0.053*** & -0.031*** & -0.024 \\
  & (0.011) & (0.009) & (0.014) \\
First Night:Treatment & -0.143*** & -0.188*** & -0.188*** \\
  & (0.014) & (0.021) & (0.019) \\
Threshold & 0.027 & -0.016 & -0.042 \\
  & (0.021) & (0.018) & (0.024) \\
Treatment:Threshold & 0.040* & 0.127*** & 0.127*** \\
  & (0.019) & (0.038) & (0.033) \\
Time Delta & -0.002* & $<$0.001 & 0.004 \\
  & (0.001) & (0.001) & (0.002) \\
Time Delta:Treatment &   & -0.005** & -0.005*** \\
  &   & (0.002) & (0.002) \\
Treatment & -0.155*** & -0.198*** & -0.198*** \\
  & (0.012) & (0.021) & (0.017) \\
Weekday & -0.008*** & -0.008*** & -0.008*** \\
  & (0.002) & (0.002) & (0.002) \\
Time Delta ** 2 &   &   & -$<$0.001 \\
  &   &   & ($<$0.001) \\
Time Delta ** 3 &   &   & -$<$0.001 \\
  &   &   & ($<$0.001) \\
R-squared & 0.844 & 0.863 & 0.873 \\
Adjusted R-squared & 0.824 & 0.843 & 0.849 \\
No. observations & 64 & 64 & 64 \\
\bottomrule
\end{tabular}

In [34]:
# Shut down the kernel to release memory
import IPython

app = IPython.Application.instance()
app.kernel.do_shutdown(restart=False)

{'status': 'ok', 'restart': False}